### ISSUE TITLE
Test transport failure cases

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zb-transport#20]
In the transport, we interact with various java nio APIs that can throw various exceptions. All of these cases should be covered.

Challenge:

* it is not possible to mock/wrap the SocketChannel API to control its behavior. That is because the sun implementations are final classes (=> no spying with Mockito) and they make instanceof checks (=> no wrapping). since the API is rather extensive, correct mocking without making assumptions about the code under test is not trivial either

**Comment by menski** [comment]
moved to https://github.com/zeebe-io/zeebe/issues/512
