### ISSUE TITLE
Simplify API

### ISSUE THREAD

**Issue by ThorbenLindhauer** [zeebe-io/zb-transport#25]

**Comment by saig0** [comment]
**Review Hints:**
* Client/Server Transport Builder: expect a dispatcher with subscription of name "sender" -> just open a new subscription
* add Java Doc for interfaces and public methods -> would help a lot to understand the API
* ZeebeClientImpl: read properties is a fail-safe way -> maybe a new issue
* SubscriptionManager: make use of transport's openSubscription
* SingleMessageTest: allocated direct buffer is not closed -> use BufferAllocators + close
* TransportChannelListenerTest: actor scheduler is not closed
